# Chatbot Model Implementation

# Import necessary libraries
from nltk.chat.util import Chat, reflections

class ChatbotModel:
    def __init__(self, pairs):
        """
        Initialize the ChatbotModel.

        Parameters:
        - pairs: List of pairs containing patterns and responses for the chatbot.
        """
        self.chatbot = Chat(pairs, reflections)

    def respond(self, input_text):
        """
        Generate a response to the input text.

        Parameters:
        - input_text: The input text provided by the user.

        Returns:
        - response: The response generated by the chatbot.
        """
        return self.chatbot.respond(input_text)
